dbt_modeling:
  outputs:
    dev:
      dbname: dev
      host: <REDSHIFT_ENDPOINT>
      password: <YOUR_REDSHIFT_PASSWORD>
      port: 5439
      schema: deftunes_serving
      threads: 1
      type: redshift
      user: defaultuser
  target: dev